#!/usr/bin/env bash

[[ -d ~/.vim/undo ]] || mkdir ~/.vim/undo

while read file; do
    [[ -e ~/."$file" ]] && rm -r ~/."$file"
done < ~/.dotfiles/hooks/excludes

while read dir; do
   [[ -L ~/"$dir" ]] || ln -fFs ~/.dotfiles/"$dir" ~/"$dir"
done < ~/.dotfiles/hooks/links
